/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Comment {
  type: 'Line' | 'Block'
  value: string
  start: number
  end: number
}

export interface ErrorLabel {
  message: string | null
  start: number
  end: number
}

export interface OxcError {
  severity: Severity
  message: string
  labels: Array<ErrorLabel>
  helpMessage: string | null
  codeframe: string | null
}

export declare const enum Severity {
  Error = 'Error',
  Warning = 'Warning',
  Advice = 'Advice'
}
export interface Comment {
  type: 'Line' | 'Block'
  value: string
  start: number
  end: number
}

export interface DynamicImport {
  start: number
  end: number
  moduleRequest: Span
}

export interface EcmaScriptModule {
  /** Has ESM syntax, such as import/export statements or `import.meta`. */
  hasModuleSyntax: boolean
  /** Import statements. */
  staticImports: Array<StaticImport>
  /** Export statements. */
  staticExports: Array<StaticExport>
  /** Dynamic import expressions. */
  dynamicImports: Array<DynamicImport>
  /** Span positions of `import.meta`. */
  importMetas: Array<Span>
}

export interface ErrorLabel {
  message: string | null
  start: number
  end: number
}

export interface ExportExportName {
  kind: ExportExportNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ExportExportNameKind {
  Name = 'Name',
  Default = 'Default',
  None = 'None'
}

export interface ExportImportName {
  kind: ExportImportNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ExportImportNameKind {
  Name = 'Name',
  All = 'All',
  AllButDefault = 'AllButDefault',
  None = 'None'
}

export interface ExportLocalName {
  kind: ExportLocalNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ExportLocalNameKind {
  Name = 'Name',
  Default = 'Default',
  None = 'None'
}

/**
 * Format a file with the given options.
 *
 * This function supports multiple file types:
 * - JavaScript/TypeScript files (via oxc_formatter)
 * - TOML files (via oxc_toml)
 * - JSON/JSON5/JSONC files (via native Rust formatters)
 * - Other files (via external formatter callbacks when napi feature is enabled)
 */
export declare function format(filename: string, sourceText: string, options?: any | undefined | null, initExternalFormatterCb?: (numThreads: number) => Promise<string[]>, formatEmbeddedCb?: (options: Record<string, any>, tagName: string, code: string) => Promise<string>, formatFileCb?: (options: Record<string, any>, parserName: string, fileName: string, code: string) => Promise<string>): Promise<FormatResult>

export interface FormatResult {
  /** The formatted code. */
  code: string
  /** Parse and format errors. */
  errors: Array<string>
}

export interface ImportName {
  kind: ImportNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ImportNameKind {
  Name = 'Name',
  NamespaceObject = 'NamespaceObject',
  Default = 'Default'
}

/** Run the oxlint-compatible linter. */
export declare function lint(args: Array<string>): Promise<boolean>

/** Run the oxlint-compatible linter synchronously. */
export declare function lintSync(args: Array<string>): boolean

/** Run the oxlint-compatible linter with JavaScript plugin callbacks. */
export declare function lintWithPlugins(args: Array<string>, loadPlugin: JsLoadPluginCb, setupRuleConfigs: JsSetupRuleConfigsCb, lintFile: JsLintFileCb, createWorkspace: JsCreateWorkspaceCb, destroyWorkspace: JsDestroyWorkspaceCb, loadJsConfigs: JsLoadJsConfigsCb): Promise<boolean>

export interface OxcError {
  severity: Severity
  message: string
  labels: Array<ErrorLabel>
  helpMessage: string | null
  codeframe: string | null
}

/** Parse JS/TS/ArkTS source text and return an ESTree-compatible AST. */
export declare function parse(filename: string, sourceText: string, options?: ParserOptions | undefined | null): Promise<ParseResult>

export interface ParseResult {
  /** ESTree-compatible AST object. */
  program: any
  module: EcmaScriptModule
  comments: Array<Comment>
  errors: Array<OxcError>
}

export interface ParserOptions {
  /** Treat the source text as `js`, `jsx`, `ts`, `tsx`, `dts` or `ets`. */
  lang?: 'js' | 'jsx' | 'ts' | 'tsx' | 'dts' | 'ets'
  /** Treat the source text as `script`, `module`, `commonjs` or `unambiguous` code. */
  sourceType?: 'script' | 'module' | 'commonjs' | 'unambiguous' | undefined
  /** Return an AST which includes TypeScript-related properties, or excludes them. */
  astType?: 'js' | 'ts'
  /** Controls whether the `range` property is included on AST nodes. */
  range?: boolean
  /** Emit `ParenthesizedExpression` and `TSParenthesizedType` in AST. */
  preserveParens?: boolean
  /** Produce semantic errors with an additional AST pass. */
  showSemanticErrors?: boolean
}

export declare const enum Severity {
  Error = 'Error',
  Warning = 'Warning',
  Advice = 'Advice'
}

export interface Span {
  start: number
  end: number
}

export interface StaticExport {
  start: number
  end: number
  entries: Array<StaticExportEntry>
}

export interface StaticExportEntry {
  start: number
  end: number
  /** Re-export source, if this export comes from another module. */
  moduleRequest: ValueSpan | null
  /** The imported name for re-exports. */
  importName: ExportImportName
  /** The exported name. */
  exportName: ExportExportName
  /** The local name used to access the exported value. */
  localName: ExportLocalName
  /** Whether the export is a TypeScript `export type`. */
  isType: boolean
}

export interface StaticImport {
  /** Start of import statement. */
  start: number
  /** End of import statement. */
  end: number
  /** Import source. */
  moduleRequest: ValueSpan
  /** Import specifiers. Empty for `import "mod"`. */
  entries: Array<StaticImportEntry>
}

export interface StaticImportEntry {
  /** The name under which the desired binding is exported by the module. */
  importName: ImportName
  /** The local binding name. */
  localName: ValueSpan
  /** Whether this binding is for a TypeScript type-only import. */
  isType: boolean
}

export interface ValueSpan {
  value: string
  start: number
  end: number
}
/**
 * Apply fixes to source text and return the fixed code.
 *
 * - `source_text` is the original source code.
 * - `fixes_json` is a JSON string containing `Vec<Vec<JsFix>>` — an array of fix groups,
 *    one group per diagnostic which provides fixes.
 *    Each inner array should have length of 1 at minimum.
 *
 * If source text starts with a BOM, `JSFix`es must have offsets relative to the start
 * of the source text *without* the BOM.
 *
 * Each group's fixes are merged, then all merged fixes are applied to `source_text`.
 *
 * Fix ranges are converted from UTF-16 code units to UTF-8 bytes.
 */
export declare function applyFixes(sourceText: string, fixesJson: string): string | null

/**
 * Get offset within a `Uint8Array` which is aligned on `BLOCK_ALIGN`.
 *
 * Does not check that the offset is within bounds of `buffer`.
 * To ensure it always is, provide a `Uint8Array` of at least `BLOCK_SIZE + BLOCK_ALIGN` bytes.
 */
export declare function getBufferOffset(buffer: Uint8Array): number

/** JS callback to create a workspace. */
export type JsCreateWorkspaceCb =
  ((arg: string) => Promise<undefined>)

/** JS callback to destroy a workspace. */
export type JsDestroyWorkspaceCb =
  ((arg: string) => void)

/** JS callback to lint a file. */
export type JsLintFileCb =
  ((arg0: string, arg1: number, arg2: Uint8Array | undefined | null, arg3: Array<number>, arg4: Array<number>, arg5: string, arg6: string, arg7?: string | undefined | null) => string | null)

/** JS callback to load JavaScript config files. */
export type JsLoadJsConfigsCb =
  ((arg: Array<string>) => Promise<string>)

/** JS callback to load a JS plugin. */
export type JsLoadPluginCb =
  ((arg0: string, arg1: string | undefined | null, arg2: boolean, arg3?: string | undefined | null) => Promise<string>)

/** JS callback to setup configs. */
export type JsSetupRuleConfigsCb =
  ((arg: string) => string | null)

/**
 * NAPI entry point.
 *
 * JS side passes in:
 * 1. `args`: Command line arguments (process.argv.slice(2))
 * 2. `load_plugin`: Load a JS plugin from a file path.
 * 3. `setup_rule_configs`: Setup configuration options.
 * 4. `lint_file`: Lint a file.
 * 5. `create_workspace`: Create a workspace.
 * 6. `destroy_workspace`: Destroy a workspace.
 * 7. `load_js_configs`: Load JavaScript config files.
 *
 * Returns `true` if linting succeeded without errors, `false` otherwise.
 */
export declare function lint(args: Array<string>, loadPlugin: JsLoadPluginCb, setupRuleConfigs: JsSetupRuleConfigsCb, lintFile: JsLintFileCb, createWorkspace: JsCreateWorkspaceCb, destroyWorkspace: JsDestroyWorkspaceCb, loadJsConfigs: JsLoadJsConfigsCb): Promise<boolean>

/**
 * Parse AST into provided `Uint8Array` buffer, synchronously.
 *
 * Source text must be written into somewhere towards end of the buffer.
 * - `source_start` is position of first byte of source text in buffer
 * - `source_len` is length of source text (in UTF-8 bytes)
 *
 * This function will parse the source, and write the AST into the buffer, starting at the end (before the source text).
 *
 * It also writes to the very end of the buffer the offset of `Program` within the buffer.
 *
 * Caller can deserialize data from the buffer on JS side.
 *
 * # SAFETY
 *
 * Caller must ensure:
 * * Source text is written into the buffer.
 * * Start of source text is at `source_start` bytes from the start of the buffer.
 * * Source text's UTF-8 byte length is `source_len`.
 * * This section of bytes in the buffer comprises a valid UTF-8 string.
 *
 * If source text is originally a JS string on JS side, and converted to a buffer with
 * `Buffer.from(str)` or `new TextEncoder().encode(str)`, this guarantees it's valid UTF-8.
 *
 * # Panics
 *
 * Panics if source text is too long, or AST takes more memory than is available in the buffer.
 */
export declare function parseRawSync(filename: string, buffer: Uint8Array, sourceStart: number, sourceLen: number, options?: ParserOptions | undefined | null): void

export interface ParserOptions {
  /** Treat the source text as `js`, `jsx`, `ts`, `tsx` or `dts`. */
  lang?: 'js' | 'jsx' | 'ts' | 'tsx' | 'dts'
  /** Treat the source text as `script` or `module` code. */
  sourceType?: 'script' | 'module' | 'commonjs' | 'unambiguous' | undefined
  /** Ignore non-fatal parsing errors */
  ignoreNonFatalErrors?: boolean
}

/** Returns `true` if raw transfer is supported on this platform. */
export declare function rawTransferSupported(): boolean
