/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Comment {
  type: 'Line' | 'Block'
  value: string
  start: number
  end: number
}

export interface DynamicImport {
  start: number
  end: number
  moduleRequest: Span
}

export interface EcmaScriptModule {
  /** Has ESM syntax, such as import/export statements or `import.meta`. */
  hasModuleSyntax: boolean
  /** Import statements. */
  staticImports: Array<StaticImport>
  /** Export statements. */
  staticExports: Array<StaticExport>
  /** Dynamic import expressions. */
  dynamicImports: Array<DynamicImport>
  /** Span positions of `import.meta`. */
  importMetas: Array<Span>
}

export interface ErrorLabel {
  message: string | null
  start: number
  end: number
}

export interface ExportExportName {
  kind: ExportExportNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ExportExportNameKind {
  Name = 'Name',
  Default = 'Default',
  None = 'None'
}

export interface ExportImportName {
  kind: ExportImportNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ExportImportNameKind {
  Name = 'Name',
  All = 'All',
  AllButDefault = 'AllButDefault',
  None = 'None'
}

export interface ExportLocalName {
  kind: ExportLocalNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ExportLocalNameKind {
  Name = 'Name',
  Default = 'Default',
  None = 'None'
}

/**
 * Format a file with the given options.
 *
 * This function supports multiple file types:
 * - JavaScript/TypeScript files (via oxc_formatter)
 * - TOML files (via oxc_toml)
 * - Other files (via external formatter callbacks when napi feature is enabled)
 */
export declare function format(filename: string, sourceText: string, options?: any | undefined | null, initExternalFormatterCb?: (numThreads: number) => Promise<string[]>, formatEmbeddedCb?: (options: Record<string, any>, tagName: string, code: string) => Promise<string>, formatFileCb?: (options: Record<string, any>, parserName: string, fileName: string, code: string) => Promise<string>): Promise<FormatResult>

export interface FormatResult {
  /** The formatted code. */
  code: string
  /** Parse and format errors. */
  errors: Array<string>
}

export interface ImportName {
  kind: ImportNameKind
  name: string | null
  start: number | null
  end: number | null
}

export declare const enum ImportNameKind {
  Name = 'Name',
  NamespaceObject = 'NamespaceObject',
  Default = 'Default'
}

export interface OxcError {
  severity: Severity
  message: string
  labels: Array<ErrorLabel>
  helpMessage: string | null
  codeframe: string | null
}

/** Parse JS/TS/ArkTS source text and return an ESTree-compatible AST. */
export declare function parse(filename: string, sourceText: string, options?: ParserOptions | undefined | null): Promise<ParseResult>

export interface ParseResult {
  /** ESTree-compatible AST object. */
  program: any
  module: EcmaScriptModule
  comments: Array<Comment>
  errors: Array<OxcError>
}

export interface ParserOptions {
  /** Treat the source text as `js`, `jsx`, `ts`, `tsx`, `dts` or `ets`. */
  lang?: 'js' | 'jsx' | 'ts' | 'tsx' | 'dts' | 'ets'
  /** Treat the source text as `script`, `module`, `commonjs` or `unambiguous` code. */
  sourceType?: 'script' | 'module' | 'commonjs' | 'unambiguous' | undefined
  /** Return an AST which includes TypeScript-related properties, or excludes them. */
  astType?: 'js' | 'ts'
  /** Controls whether the `range` property is included on AST nodes. */
  range?: boolean
  /** Emit `ParenthesizedExpression` and `TSParenthesizedType` in AST. */
  preserveParens?: boolean
  /** Produce semantic errors with an additional AST pass. */
  showSemanticErrors?: boolean
}

export declare const enum Severity {
  Error = 'Error',
  Warning = 'Warning',
  Advice = 'Advice'
}

export interface Span {
  start: number
  end: number
}

export interface StaticExport {
  start: number
  end: number
  entries: Array<StaticExportEntry>
}

export interface StaticExportEntry {
  start: number
  end: number
  /** Re-export source, if this export comes from another module. */
  moduleRequest: ValueSpan | null
  /** The imported name for re-exports. */
  importName: ExportImportName
  /** The exported name. */
  exportName: ExportExportName
  /** The local name used to access the exported value. */
  localName: ExportLocalName
  /** Whether the export is a TypeScript `export type`. */
  isType: boolean
}

export interface StaticImport {
  /** Start of import statement. */
  start: number
  /** End of import statement. */
  end: number
  /** Import source. */
  moduleRequest: ValueSpan
  /** Import specifiers. Empty for `import "mod"`. */
  entries: Array<StaticImportEntry>
}

export interface StaticImportEntry {
  /** The name under which the desired binding is exported by the module. */
  importName: ImportName
  /** The local binding name. */
  localName: ValueSpan
  /** Whether this binding is for a TypeScript type-only import. */
  isType: boolean
}

export interface ValueSpan {
  value: string
  start: number
  end: number
}
